language: php

php:
    - 7.1
    - 7.2

env:
    matrix:
        - PREFER_LOWEST="--prefer-lowest"
        - PREFER_LOWEST=""

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist $PREFER_LOWEST

script:
    - composer validate --strict

    - vendor/bin/ecs check src spec

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/behat --strict -vvv --no-interaction
