language: php

php:
    - 7.1
    - 7.2

env:
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.0.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/behat --strict -vvv --no-interaction

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.1

            script:
                - vendor/bin/ecs check src spec
